/**
 * Auto-generated by \`npm run ingest:svgs\`.
 * Prefer local tabler-icons/icons/outline, then assets/raw-svgs overrides.
 * Do not edit by hand — update assets/ingest-manifest.json.
 */
import type { VisualAsset } from "@/lib/visuals/types";

export const GENERATED_ASSETS: VisualAsset[] = [
  {
    "id": "tabler-horse",
    "title": "Horse",
    "viewBox": "0 0 24 24",
    "tags": [
      "horse",
      "horseriding",
      "horse anatomy",
      "equestrian",
      "stallion",
      "equine",
      "mare",
      "pony",
      "steed",
      "riding",
      "hoofed animal",
      "horseback",
      "thoroughbred"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M7 10l-.85 8.507a1.357 1.357 0 0 0 1.35 1.493h.146a2 2 0 0 0 1.857 -1.257l.994 -2.486a2 2 0 0 1 1.857 -1.257h1.292a2 2 0 0 1 1.857 1.257l.994 2.486a2 2 0 0 0 1.857 1.257h.146a1.37 1.37 0 0 0 1.364 -1.494l-.864 -9.506h-8c0 -3 -3 -5 -6 -5l-3 6l2 2l3 -2",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M22 14v-2a3 3 0 0 0 -3 -3",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-heart",
    "title": "Heart",
    "viewBox": "0 0 24 24",
    "tags": [
      "heart",
      "human heart",
      "parts of the heart",
      "blood",
      "love",
      "emotion",
      "like",
      "favorite",
      "relationship",
      "geometry",
      "form",
      "figure",
      "pattern"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-hexagon",
    "title": "Hexagon",
    "viewBox": "0 0 24 24",
    "tags": [
      "hexagon",
      "six sides",
      "polygon",
      "shape",
      "geometric",
      "math",
      "2d",
      "geometry",
      "form",
      "figure",
      "pattern",
      "outline"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M19.875 6.27a2.225 2.225 0 0 1 1.125 1.948v7.284c0 .809 -.443 1.555 -1.158 1.948l-6.75 4.27a2.269 2.269 0 0 1 -2.184 0l-6.75 -4.27a2.225 2.225 0 0 1 -1.158 -1.948v-7.285c0 -.809 .443 -1.554 1.158 -1.947l6.75 -3.98a2.33 2.33 0 0 1 2.25 0l6.75 3.98h-.033",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "eye-simple",
    "title": "Eye",
    "viewBox": "0 0 24 24",
    "tags": [
      "eye",
      "parts of the eye",
      "eye cross section",
      "vision",
      "view",
      "watch",
      "control",
      "operation",
      "function",
      "interface",
      "management",
      "visibility",
      "accessibility",
      "a11y"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tree-simple",
    "title": "Tree",
    "viewBox": "0 0 24 24",
    "tags": [
      "tree",
      "parts of a tree",
      "roots",
      "trunk",
      "leaves",
      "nature",
      "greenery",
      "park",
      "leaf",
      "stem",
      "root",
      "forest",
      "garden"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M12 13l-2 -2",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M12 12l2 -2",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M12 21v-13",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M9.824 16a3 3 0 0 1 -2.743 -3.69a3 3 0 0 1 .304 -4.833a3 3 0 0 1 4.615 -3.707a3 3 0 0 1 4.614 3.707a3 3 0 0 1 .305 4.833a3 3 0 0 1 -2.919 3.695h-4l-.176 -.005",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "solar-planet",
    "title": "Planet / orbit",
    "viewBox": "0 0 24 24",
    "tags": [
      "solar system",
      "planet",
      "orbit",
      "planets in order",
      "earth",
      "uranus",
      "universe",
      "space",
      "galaxy",
      "atmosphere",
      "location",
      "navigation"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M18.816 13.58c2.292 2.138 3.546 4 3.092 4.9c-.745 1.46 -5.783 -.259 -11.255 -3.838c-5.47 -3.579 -9.304 -7.664 -8.56 -9.123c.464 -.91 2.926 -.444 5.803 .805",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M5 12a7 7 0 1 0 14 0a7 7 0 1 0 -14 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "solar-sun",
    "title": "Sun",
    "viewBox": "0 0 24 24",
    "tags": [
      "sun",
      "solar system",
      "star",
      "weather",
      "light",
      "mode",
      "brightness",
      "climate",
      "forecast",
      "meteorology",
      "atmospheric",
      "conditions"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "globe-simple",
    "title": "Globe / Earth",
    "viewBox": "0 0 24 24",
    "tags": [
      "earth",
      "globe",
      "world",
      "planet earth",
      "travel",
      "journey",
      "trip",
      "planet",
      "location",
      "navigation",
      "geography"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M7 9a4 4 0 1 0 8 0a4 4 0 0 0 -8 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M5.75 15a8.015 8.015 0 1 0 9.25 -13",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M11 17v4",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M7 21h8",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "water-drop",
    "title": "Water drop",
    "viewBox": "0 0 24 24",
    "tags": [
      "water",
      "water molecule",
      "H2O",
      "droplet",
      "rain",
      "liquid",
      "creative",
      "artistic",
      "visual",
      "aesthetic",
      "style"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M7.502 19.423c2.602 2.105 6.395 2.105 8.996 0c2.602 -2.105 3.262 -5.708 1.566 -8.546l-4.89 -7.26c-.42 -.625 -1.287 -.803 -1.936 -.397a1.376 1.376 0 0 0 -.41 .397l-4.893 7.26c-1.695 2.838 -1.035 6.441 1.567 8.546",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "atom-simple",
    "title": "Atom",
    "viewBox": "0 0 24 24",
    "tags": [
      "atom",
      "molecule",
      "chemistry",
      "water molecule",
      "unit",
      "part",
      "electrons",
      "particle",
      "science",
      "physics"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M12 12v.01",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M19.071 4.929c-1.562 -1.562 -6 .337 -9.9 4.243c-3.905 3.905 -5.804 8.337 -4.242 9.9c1.562 1.561 6 -.338 9.9 -4.244c3.905 -3.905 5.804 -8.337 4.242 -9.9",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M4.929 4.929c-1.562 1.562 .337 6 4.243 9.9c3.905 3.905 8.337 5.804 9.9 4.242c1.561 -1.562 -.338 -6 -4.244 -9.9c-3.905 -3.905 -8.337 -5.804 -9.9 -4.242",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "flask-simple",
    "title": "Flask",
    "viewBox": "0 0 24 24",
    "tags": [
      "chemistry",
      "flask",
      "reaction",
      "liquid",
      "container",
      "glass",
      "test",
      "laboratory",
      "experimental",
      "beta",
      "medical"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M9 3l6 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M10 9l4 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M10 3v6l-4 11a.7 .7 0 0 0 .5 1h11a.7 .7 0 0 0 .5 -1l-4 -11v-6",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "rocket-simple",
    "title": "Rocket",
    "viewBox": "0 0 24 24",
    "tags": [
      "rocket",
      "rocket launch",
      "escape velocity",
      "universe",
      "galaxy",
      "space",
      "journey",
      "discover",
      "extraterrestrial",
      "spaceship",
      "location",
      "navigation"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M4 13a8 8 0 0 1 7 7a6 6 0 0 0 3 -5a9 9 0 0 0 6 -8a3 3 0 0 0 -3 -3a9 9 0 0 0 -8 6a6 6 0 0 0 -5 3",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M7 14a6 6 0 0 0 -3 6a6 6 0 0 0 6 -3",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M14 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "leaf-simple",
    "title": "Leaf",
    "viewBox": "0 0 24 24",
    "tags": [
      "leaf",
      "photosynthesis",
      "plant",
      "nature",
      "tree",
      "autumn",
      "fall",
      "greenery",
      "flower",
      "forest",
      "garden"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M5 21c.5 -4.5 2.5 -8 7 -10",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M9 18c6.218 0 10.5 -3.288 11 -12v-2h-4.014c-9 0 -11.986 4 -12 9c0 1 0 3 2 5h3l.014 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "recycle-cycle",
    "title": "Recycle / cycle",
    "viewBox": "0 0 24 24",
    "tags": [
      "recycle",
      "water cycle",
      "rock cycle",
      "cycle",
      "trash",
      "rubbish",
      "recyclable",
      "reuse",
      "waste",
      "sign",
      "mark",
      "emblem",
      "representation"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M12 17l-2 2l2 2",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M10 19h9a2 2 0 0 0 1.75 -2.75l-.55 -1",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M8.536 11l-.732 -2.732l-2.732 .732",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M7.804 8.268l-4.5 7.794a2 2 0 0 0 1.506 2.89l1.141 .024",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M15.464 11l2.732 .732l.732 -2.732",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M18.196 11.732l-4.5 -7.794a2 2 0 0 0 -3.256 -.14l-.591 .976",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "refresh-loop",
    "title": "Refresh loop",
    "viewBox": "0 0 24 24",
    "tags": [
      "loop",
      "cycle",
      "repeat",
      "refresh",
      "synchronization",
      "reload",
      "restart",
      "spinner",
      "loader",
      "ajax",
      "update",
      "arrows",
      "navigation"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M20 11a8.1 8.1 0 0 0 -15.5 -2m-.5 -4v4h4",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M4 13a8.1 8.1 0 0 0 15.5 2m.5 4v-4h-4",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "timeline-process",
    "title": "Timeline / process",
    "viewBox": "0 0 24 24",
    "tags": [
      "process",
      "timeline",
      "bill becomes law",
      "legislative",
      "plan",
      "planning",
      "diagram",
      "chart",
      "roadmap"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M4 16l6 -7l5 5l5 -6",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M14 14a1 1 0 1 0 2 0a1 1 0 1 0 -2 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M9 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M3 16a1 1 0 1 0 2 0a1 1 0 1 0 -2 0",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M19 8a1 1 0 1 0 2 0a1 1 0 1 0 -2 0",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "route-journey",
    "title": "Route / journey",
    "viewBox": "0 0 24 24",
    "tags": [
      "journey",
      "digestion",
      "path",
      "route",
      "direction",
      "trail",
      "navigate",
      "travel",
      "way",
      "road",
      "travel route",
      "route way"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M19 7a2 2 0 1 0 0 -4a2 2 0 0 0 0 4",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M11 19h5.5a3.5 3.5 0 0 0 0 -7h-8a3.5 3.5 0 0 1 0 -7h4.5",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "mountain-rock",
    "title": "Mountain / rock",
    "viewBox": "0 0 24 24",
    "tags": [
      "rock cycle",
      "mountain",
      "geology",
      "alps",
      "camping",
      "mount everest",
      "trekking",
      "environment",
      "natural",
      "outdoor",
      "ecosystem",
      "earth"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 20h18l-6.921 -14.612a2.3 2.3 0 0 0 -4.158 0l-6.921 14.612",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M7.5 11l2 2.5l2.5 -2.5l2 3l2.5 -2",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "volcano-igneous",
    "title": "Volcano",
    "viewBox": "0 0 24 24",
    "tags": [
      "volcano",
      "igneous",
      "rock cycle",
      "erumption",
      "lava",
      "nature",
      "danger",
      "explosion",
      "location",
      "navigation",
      "geography",
      "place"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M9 8v-1a2 2 0 1 0 -4 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M15 8v-1a2 2 0 1 1 4 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M4 20l3.472 -7.812a2 2 0 0 1 1.828 -1.188h5.4a2 2 0 0 1 1.828 1.188l3.472 7.812",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M6.192 15.064a2.14 2.14 0 0 1 .475 -.064c.527 -.009 1.026 .178 1.333 .5c.307 .32 .806 .507 1.333 .5c.527 .007 1.026 -.18 1.334 -.5c.307 -.322 .806 -.509 1.333 -.5c.527 -.009 1.026 .178 1.333 .5c.308 .32 .807 .507 1.334 .5c.527 .007 1.026 -.18 1.333 -.5c.307 -.322 .806 -.509 1.333 -.5c.161 .003 .32 .025 .472 .064",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M12 8v-4",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-stack",
    "title": "Stack",
    "viewBox": "0 0 24 24",
    "tags": [
      "stack",
      "lifo",
      "stack data structure",
      "pile",
      "elements",
      "layout",
      "wrap",
      "creative",
      "artistic",
      "visual",
      "aesthetic",
      "style"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M12 4l-8 4l8 4l8 -4l-8 -4",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M4 12l8 4l8 -4",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M4 16l8 4l8 -4",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-stack-push",
    "title": "Stack push",
    "viewBox": "0 0 24 24",
    "tags": [
      "stack push",
      "push",
      "lifo",
      "arrange",
      "data",
      "level",
      "layout",
      "arrow",
      "stack",
      "creative",
      "artistic",
      "visual"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M6 10l-2 1l8 4l8 -4l-2 -1",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M4 15l8 4l8 -4",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M12 4v7",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M15 8l-3 3l-3 -3",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-queue-people",
    "title": "People line",
    "viewBox": "0 0 24 24",
    "tags": [
      "queue",
      "fifo",
      "line",
      "people",
      "community",
      "team",
      "cluster",
      "society",
      "gathering",
      "crowd",
      "network",
      "collective",
      "assembly",
      "fellowship"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M17 10h2a2 2 0 0 1 2 2v1",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M3 13v-1a2 2 0 0 1 2 -2h2",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-box",
    "title": "Box",
    "viewBox": "0 0 24 24",
    "tags": [
      "variable",
      "box",
      "value",
      "cube",
      "app",
      "application",
      "package",
      "container"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M12 3l8 4.5l0 9l-8 4.5l-8 -4.5l0 -9l8 -4.5",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M12 12l8 -4.5",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M12 12l0 9",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M12 12l-8 -4.5",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-function",
    "title": "Function",
    "viewBox": "0 0 24 24",
    "tags": [
      "function",
      "functions",
      "math function",
      "math",
      "linear",
      "statyscics",
      "graph",
      "calculation",
      "equation",
      "mathematics",
      "numeric",
      "formula"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M4 6.667a2.667 2.667 0 0 1 2.667 -2.667h10.666a2.667 2.667 0 0 1 2.667 2.667v10.666a2.667 2.667 0 0 1 -2.667 2.667h-10.666a2.667 2.667 0 0 1 -2.667 -2.667l0 -10.666",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M9 15.5v.25c0 .69 .56 1.25 1.25 1.25c.71 0 1.304 -.538 1.374 -1.244l.752 -7.512a1.381 1.381 0 0 1 1.374 -1.244c.69 0 1.25 .56 1.25 1.25v.25",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M9 12h6",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-binary",
    "title": "Binary",
    "viewBox": "0 0 24 24",
    "tags": [
      "binary",
      "bits",
      "ones and zeros",
      "code",
      "digital",
      "computer",
      "programming",
      "data",
      "bit",
      "byte",
      "numeric",
      "computing"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M11 10v-5h-1m8 14v-5h-1",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M15 5.5a.5 .5 0 0 1 .5 -.5h2a.5 .5 0 0 1 .5 .5v4a.5 .5 0 0 1 -.5 .5h-2a.5 .5 0 0 1 -.5 -.5l0 -4",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M10 14.5a.5 .5 0 0 1 .5 -.5h2a.5 .5 0 0 1 .5 .5v4a.5 .5 0 0 1 -.5 .5h-2a.5 .5 0 0 1 -.5 -.5l0 -4",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M6 10h.01m-.01 9h.01",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-git-branch",
    "title": "Branch",
    "viewBox": "0 0 24 24",
    "tags": [
      "inheritance",
      "extends",
      "git branch",
      "is-a",
      "code",
      "version control",
      "command",
      "git",
      "branch",
      "versioning",
      "repository",
      "tracking",
      "revision"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M5 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M15 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M7 8l0 8",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M9 18h6a2 2 0 0 0 2 -2v-5",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M14 14l3 -3l3 3",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-lock",
    "title": "Lock",
    "viewBox": "0 0 24 24",
    "tags": [
      "encryption",
      "encrypt",
      "lock",
      "security",
      "password",
      "secure",
      "private",
      "control",
      "operation",
      "protected",
      "closed",
      "function"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M5 13a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-6",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M11 16a1 1 0 1 0 2 0a1 1 0 0 0 -2 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M8 11v-4a4 4 0 1 1 8 0v4",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-key",
    "title": "Key",
    "viewBox": "0 0 24 24",
    "tags": [
      "encryption",
      "key",
      "public key",
      "password",
      "login",
      "authentication",
      "secure"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M16.555 3.843l3.602 3.602a2.877 2.877 0 0 1 0 4.069l-2.643 2.643a2.877 2.877 0 0 1 -4.069 0l-.301 -.301l-6.558 6.558a2 2 0 0 1 -1.239 .578l-.175 .008h-1.172a1 1 0 0 1 -.993 -.883l-.007 -.117v-1.172a2 2 0 0 1 .467 -1.284l.119 -.13l.414 -.414h2v-2h2v-2l2.144 -2.144l-.301 -.301a2.877 2.877 0 0 1 0 -4.069l2.643 -2.643a2.877 2.877 0 0 1 4.069 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M15 9h.01",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-api",
    "title": "API",
    "viewBox": "0 0 24 24",
    "tags": [
      "api",
      "rest api",
      "how apis work",
      "programming",
      "coding",
      "program",
      "code",
      "configuration",
      "software",
      "technical",
      "developer",
      "interface"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M4 13h5",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M12 16v-8h3a2 2 0 0 1 2 2v1a2 2 0 0 1 -2 2h-3",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M20 8v8",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M9 16v-5.5a2.5 2.5 0 0 0 -5 0v5.5",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-server",
    "title": "Server",
    "viewBox": "0 0 24 24",
    "tags": [
      "server",
      "api",
      "backend",
      "storage",
      "hosting",
      "www",
      "hardware",
      "technology",
      "electronic",
      "gadget",
      "equipment"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 7a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-2",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M3 15a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3l0 -2",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M7 8l0 .01",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M7 16l0 .01",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-pointer",
    "title": "Pointer",
    "viewBox": "0 0 24 24",
    "tags": [
      "pointer",
      "cursor",
      "mouse",
      "point",
      "click",
      "arrow",
      "control",
      "operation",
      "function",
      "interface"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M7.904 17.563a1.2 1.2 0 0 0 2.228 .308l2.09 -3.093l4.907 4.907a1.067 1.067 0 0 0 1.509 0l1.047 -1.047a1.067 1.067 0 0 0 0 -1.509l-4.907 -4.907l3.113 -2.09a1.2 1.2 0 0 0 -.309 -2.228l-13.582 -3.904l3.904 13.563",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-link",
    "title": "Link / reference",
    "viewBox": "0 0 24 24",
    "tags": [
      "reference",
      "pointer",
      "link",
      "reference vs value",
      "zoom filled",
      "url",
      "connection",
      "hyperlink",
      "attach",
      "join",
      "typography",
      "writing"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M9 15l6 -6",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M11 6l.463 -.536a5 5 0 0 1 7.071 7.072l-.534 .464",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M13 18l-.397 .534a5.068 5.068 0 0 1 -7.127 0a4.972 4.972 0 0 1 0 -7.071l.524 -.463",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-arrows-join",
    "title": "Arrows join",
    "viewBox": "0 0 24 24",
    "tags": [
      "reference",
      "join",
      "point to",
      "direction",
      "east",
      "arrows",
      "navigation",
      "flow",
      "movement",
      "route",
      "path",
      "pointers"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 7h5l3.5 5h9.5",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M3 17h5l3.495 -5",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M18 15l3 -3l-3 -3",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-layers",
    "title": "Layers",
    "viewBox": "0 0 24 24",
    "tags": [
      "layers",
      "recursion",
      "nested",
      "layered intersection",
      "layer difference",
      "intersecting",
      "layer overlap",
      "intersection",
      "intersecting layers",
      "layer interaction",
      "layer cross",
      "layers crossing",
      "layer junction",
      "stack"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M8 6a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2l0 -8",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M4 10a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2l0 -8",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-components",
    "title": "Components / blueprint",
    "viewBox": "0 0 24 24",
    "tags": [
      "components",
      "blueprint",
      "template",
      "class",
      "hardware",
      "technology",
      "electronic",
      "computer",
      "design",
      "ux",
      "figma",
      "creative",
      "artistic"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 12l3 3l3 -3l-3 -3l-3 3",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M15 12l3 3l3 -3l-3 -3l-3 3",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M9 6l3 3l3 -3l-3 -3l-3 3",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M9 18l3 3l3 -3l-3 -3l-3 3",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "supply-demand-curves",
    "title": "Line chart",
    "viewBox": "0 0 24 24",
    "tags": [
      "supply and demand",
      "equilibrium",
      "curves",
      "statistics",
      "diagram",
      "graph",
      "rhythm",
      "data",
      "analysis",
      "chart",
      "line",
      "visualization",
      "analytics"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M4 19l16 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M4 15l4 -6l4 2l4 -5l4 4",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "chart-area",
    "title": "Area chart",
    "viewBox": "0 0 24 24",
    "tags": [
      "growth",
      "compound interest",
      "area chart",
      "statistics",
      "diagram",
      "graph",
      "rhythm",
      "data",
      "analysis",
      "chart",
      "area",
      "line",
      "visualization"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M4 19l4 -6l4 2l4 -5l4 4l0 5l-16 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M4 12l3 -4l4 2l5 -6l4 4",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "compound-growth",
    "title": "Snowflake / growth",
    "viewBox": "0 0 24 24",
    "tags": [
      "compound interest",
      "exponential growth",
      "snowball",
      "winter",
      "weather",
      "cold",
      "frost",
      "snowflake",
      "climate",
      "forecast",
      "meteorology",
      "atmospheric",
      "conditions"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M10 4l2 1l2 -1",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M12 2v6.5l3 1.72",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M17.928 6.268l.134 2.232l1.866 1.232",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M20.66 7l-5.629 3.25l.01 3.458",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M19.928 14.268l-1.866 1.232l-.134 2.232",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M20.66 17l-5.629 -3.25l-2.99 1.738",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p7",
        "d": "M14 20l-2 -1l-2 1",
        "drawOrder": 7,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p8",
        "d": "M12 22v-6.5l-3 -1.72",
        "drawOrder": 8,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p9",
        "d": "M6.072 17.732l-.134 -2.232l-1.866 -1.232",
        "drawOrder": 9,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p10",
        "d": "M3.34 17l5.629 -3.25l-.01 -3.458",
        "drawOrder": 10,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p11",
        "d": "M4.072 9.732l1.866 -1.232l.134 -2.232",
        "drawOrder": 11,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p12",
        "d": "M3.34 7l5.629 3.25l2.99 -1.738",
        "drawOrder": 12,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-flame",
    "title": "Flame / entropy heat",
    "viewBox": "0 0 24 24",
    "tags": [
      "entropy",
      "heat",
      "thermodynamics",
      "fire",
      "fireplace",
      "light",
      "burn",
      "bonfire",
      "smoke",
      "barbecue",
      "flame"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M12 10.941c2.333 -3.308 .167 -7.823 -1 -8.941c0 3.395 -2.235 5.299 -3.667 6.706c-1.43 1.408 -2.333 3.294 -2.333 5.588c0 3.704 3.134 6.706 7 6.706c3.866 0 7 -3.002 7 -6.706c0 -1.712 -1.232 -4.403 -2.333 -5.588c-2.084 3.353 -3.257 3.353 -4.667 2.235",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-wind",
    "title": "Wind / disorder",
    "viewBox": "0 0 24 24",
    "tags": [
      "entropy",
      "disorder",
      "wind",
      "weather",
      "breeze",
      "tornado",
      "typhoon",
      "cyclone",
      "hurricane",
      "climate",
      "forecast",
      "meteorology"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M5 8h8.5a2.5 2.5 0 1 0 -2.34 -3.24",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M3 12h15.5a2.5 2.5 0 1 1 -2.34 3.24",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M4 16h5.5a2.5 2.5 0 1 1 -2.34 3.24",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-triangle",
    "title": "Triangle",
    "viewBox": "0 0 24 24",
    "tags": [
      "triangle",
      "pythagoras",
      "geometry",
      "delta",
      "shape",
      "form",
      "figure",
      "pattern",
      "outline"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-wave-sine",
    "title": "Sine wave",
    "viewBox": "0 0 24 24",
    "tags": [
      "sine",
      "sine wave",
      "unit circle",
      "trigonometry",
      "pulse",
      "signal",
      "ratio",
      "rate",
      "volume",
      "wave"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M21 12h-2c-.894 0 -1.662 -.857 -1.761 -2c-.296 -3.45 -.749 -6 -2.749 -6s-2.5 3.582 -2.5 8s-.5 8 -2.5 8s-2.452 -2.547 -2.749 -6c-.1 -1.147 -.867 -2 -1.763 -2h-2",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-circle",
    "title": "Circle",
    "viewBox": "0 0 24 24",
    "tags": [
      "circle",
      "area of a circle",
      "unit circle",
      "pi",
      "off",
      "zero",
      "round",
      "circular",
      "geometry",
      "form",
      "figure",
      "pattern",
      "outline"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-math-function",
    "title": "Math function",
    "viewBox": "0 0 24 24",
    "tags": [
      "function graph",
      "derivative",
      "y = mx + b",
      "slope",
      "linear",
      "statyscics",
      "graph",
      "math",
      "function",
      "calculation",
      "equation",
      "mathematics",
      "numeric",
      "formula"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 19a2 2 0 0 0 2 2c2 0 2 -4 3 -9s1 -9 3 -9a2 2 0 0 1 2 2",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M5 12h6",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M15 12l6 6",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M15 18l6 -6",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-vector",
    "title": "Vector",
    "viewBox": "0 0 24 24",
    "tags": [
      "vector",
      "vectors",
      "tip to tail",
      "curve",
      "parametric",
      "design",
      "vector graphics",
      "placement",
      "creative",
      "artistic",
      "visual",
      "aesthetic"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 4a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -2",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M17 4a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -2",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M17 18a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -2",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M3 18a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -2",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M5 7l0 10",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M19 7l0 10",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p7",
        "d": "M7 5l10 0",
        "drawOrder": 7,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p8",
        "d": "M7 19l10 0",
        "drawOrder": 8,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-vector-triangle",
    "title": "Vector triangle",
    "viewBox": "0 0 24 24",
    "tags": [
      "vector addition",
      "tip to tail",
      "curve",
      "parametric",
      "design",
      "vector graphics",
      "placement",
      "vector",
      "triangle",
      "creative",
      "artistic",
      "visual"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M10 5a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -2",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M3 18a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -2",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M17 18a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -2",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M6.5 17.1l5 -9.1",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M17.5 17.1l-5 -9.1",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M7 19l10 0",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-dice",
    "title": "Dice",
    "viewBox": "0 0 24 24",
    "tags": [
      "probability",
      "dice",
      "sample space",
      "chance",
      "game",
      "boardgame",
      "roll",
      "throw",
      "cube",
      "numbers",
      "gambling",
      "entertainment",
      "playing"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M8 8.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M15 8.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M15 15.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M8 15.5a.5 .5 0 1 0 1 0a.5 .5 0 1 0 -1 0",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-coin",
    "title": "Coin",
    "viewBox": "0 0 24 24",
    "tags": [
      "probability",
      "coin",
      "coin flip",
      "money",
      "earn",
      "salary",
      "change",
      "dollar",
      "store",
      "purchase",
      "shopping",
      "retail"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M14.8 9a2 2 0 0 0 -1.8 -1h-2a2 2 0 1 0 0 4h2a2 2 0 1 1 0 4h-2a2 2 0 0 1 -1.8 -1",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M12 7v10",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-pizza",
    "title": "Pizza / fractions",
    "viewBox": "0 0 24 24",
    "tags": [
      "fractions",
      "pizza",
      "parts of a whole",
      "food",
      "cheese",
      "italy",
      "pepperoni",
      "margherita",
      "capricciosa",
      "rucole",
      "meal",
      "cuisine"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M12 21.5c-3.04 0 -5.952 -.714 -8.5 -1.983l8.5 -16.517l8.5 16.517a19.09 19.09 0 0 1 -8.5 1.983",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M5.38 15.866a14.94 14.94 0 0 0 6.815 1.634a14.944 14.944 0 0 0 6.502 -1.479",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M13 11.01v-.01",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M11 14v-.01",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-matrix",
    "title": "Matrix",
    "viewBox": "0 0 24 24",
    "tags": [
      "matrix",
      "matrix multiplication",
      "linear algebra",
      "grid",
      "array",
      "system",
      "structure",
      "arrangement",
      "schema",
      "chart",
      "layout",
      "framework"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M8 16h.013",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M12.01 16h.005",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M16.015 16h.005",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M16.015 12h.005",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M8.01 12h.005",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M12.01 12h.005",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p7",
        "d": "M16.02 8h.005",
        "drawOrder": 7,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p8",
        "d": "M8.015 8h.005",
        "drawOrder": 8,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p9",
        "d": "M12.015 8h.005",
        "drawOrder": 9,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p10",
        "d": "M7 4h-1a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h1",
        "drawOrder": 10,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p11",
        "d": "M17 4h1a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-1",
        "drawOrder": 11,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-chart-dots",
    "title": "Dot chart / spread",
    "viewBox": "0 0 24 24",
    "tags": [
      "standard deviation",
      "spread",
      "mean",
      "statistics",
      "graph",
      "diagram",
      "analyticks",
      "data",
      "value",
      "variable",
      "scale",
      "statistical",
      "chart"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M3 3v18h18",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M7 15a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M11 5a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M16 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M21 3l-6 1.5",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M14.113 6.65l2.771 3.695",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p7",
        "d": "M16 12.5l-5 2",
        "drawOrder": 7,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-list-numbers",
    "title": "Number list",
    "viewBox": "0 0 24 24",
    "tags": [
      "prime numbers",
      "numbers",
      "sieve",
      "to do",
      "checklist",
      "form",
      "template",
      "task",
      "reminder",
      "schedule",
      "agenda",
      "list"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M11 6h9",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M11 12h9",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M12 18h8",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M4 16a2 2 0 1 1 4 0c0 .591 -.5 1 -1 1.5l-3 2.5h4",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M6 10v-6l-2 2",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-sort-numbers",
    "title": "Sorted numbers",
    "viewBox": "0 0 24 24",
    "tags": [
      "prime numbers",
      "sieve of eratosthenes",
      "numbers",
      "filter",
      "classify",
      "arrange",
      "order",
      "sort",
      "ascending",
      "typography",
      "writing",
      "font"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M4 15l3 3l3 -3",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M7 6v12",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M17 3a2 2 0 0 1 2 2v3a2 2 0 1 1 -4 0v-3a2 2 0 0 1 2 -2",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M15 16a2 2 0 1 0 4 0a2 2 0 1 0 -4 0",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M19 16v3a2 2 0 0 1 -2 2h-1.5",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-log-ratio",
    "title": "Division / log ratio",
    "viewBox": "0 0 24 24",
    "tags": [
      "logarithm",
      "logarithms",
      "ratio",
      "mathematic",
      "expression",
      "equation",
      "math",
      "divide",
      "calculation",
      "mathematics",
      "numeric",
      "formula",
      "x"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M9 3l6 6",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M9 9l6 -6",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M9 15l3 4.5",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M15 15l-4.5 7",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M5 12h14",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-scale",
    "title": "Scale / balance",
    "viewBox": "0 0 24 24",
    "tags": [
      "scale",
      "slope",
      "balance",
      "weigh",
      "amount",
      "heavy",
      "light",
      "libra"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M7 20l10 0",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M6 6l6 -1l6 1",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M12 3l0 17",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M9 12l-3 -6l-3 6a3 3 0 0 0 6 0",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M21 12l-3 -6l-3 6a3 3 0 0 0 6 0",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-dna",
    "title": "DNA",
    "viewBox": "0 0 24 24",
    "tags": [
      "dna",
      "biology",
      "genetics",
      "chain",
      "genetic",
      "code",
      "virus",
      "organism",
      "medical",
      "wellness"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M14.828 14.828a4 4 0 1 0 -5.656 -5.656a4 4 0 0 0 5.656 5.656",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M9.172 20.485a4 4 0 1 0 -5.657 -5.657",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M14.828 3.515a4 4 0 0 0 5.657 5.657",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-brain",
    "title": "Brain",
    "viewBox": "0 0 24 24",
    "tags": [
      "brain",
      "anatomy",
      "mind",
      "human",
      "iq",
      "inteligence",
      "organ",
      "medical",
      "wellness",
      "healthcare",
      "treatment"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M15.5 13a3.5 3.5 0 0 0 -3.5 3.5v1a3.5 3.5 0 0 0 7 0v-1.8",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M8.5 13a3.5 3.5 0 0 1 3.5 3.5v1a3.5 3.5 0 0 1 -7 0v-1.8",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p3",
        "d": "M17.5 16a3.5 3.5 0 0 0 0 -7h-.5",
        "drawOrder": 3,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p4",
        "d": "M19 9.3v-2.8a3.5 3.5 0 0 0 -7 0",
        "drawOrder": 4,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p5",
        "d": "M6.5 16a3.5 3.5 0 0 1 0 -7h.5",
        "drawOrder": 5,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p6",
        "d": "M5 9.3v-2.8a3.5 3.5 0 0 1 7 0v10",
        "drawOrder": 6,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  },
  {
    "id": "tabler-pyramid",
    "title": "Pyramid",
    "viewBox": "0 0 24 24",
    "tags": [
      "pyramid",
      "geometry",
      "3d",
      "pattern",
      "abstract",
      "geometric",
      "shape",
      "form",
      "figure",
      "outline"
    ],
    "paths": [
      {
        "id": "p1",
        "d": "M11.105 21.788a1.994 1.994 0 0 0 1.789 0l8.092 -4.054c.538 -.27 .718 -.951 .385 -1.452l-8.54 -13.836a.999 .999 0 0 0 -1.664 0l-8.54 13.836a1.005 1.005 0 0 0 .386 1.452l8.092 4.054",
        "drawOrder": 1,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      },
      {
        "id": "p2",
        "d": "M12 2v20",
        "drawOrder": 2,
        "stroke": "#7dcea0",
        "strokeWidth": 1.6
      }
    ],
    "anchors": {
      "center": {
        "x": 12,
        "y": 12,
        "preferredLabelSide": "bottom"
      },
      "top": {
        "x": 12,
        "y": 2.88,
        "preferredLabelSide": "top"
      },
      "right": {
        "x": 21.12,
        "y": 12,
        "preferredLabelSide": "right"
      }
    }
  }
];
